### PR TITLE
upgrade vertx to 3.5.1

### PR DESCRIPTION
**Pull request by gadieichhorn**
I am trying to upgrade to latest available vertx 3.5.1 

```
		<vertx.version>3.5.1</vertx.version>
		<netty.version>4.1.19.Final</netty.version>
```

IT stopped working (part of the build), any idea why?

### CODE REVIEW

**Comment by ANierbeck** [comment]
I'll try to verify this, but right now the build fails for me completely ... so need to check that beforehand.

**Comment by gadieichhorn** [comment]
I ended up wrapping the vertx jars again with exposed impl package. looking forward to see your solution :)

**Comment by ANierbeck** [comment]
see https://github.com/ANierbeck/Karaf-Vertx/pull/32

**Comment by gadieichhorn** [comment]
seemed to work, thanks :)

**Pull request merged**
